name: Build and Test

on:
  push:
    branches:
      - gtest
  pull_request:
    branches:
      - gtest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make

    - name: Configure Project with CMake
      run: |
        cmake -S . -B build

    - name: Build Project
      run: |
        cmake --build build

    - name: Run Tests with CTest
      run: |
        cd build
        ctest --output-on-failure > test_output.log

    - name: Upload Test Log
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: build/test_output.log
