name: Build and Test

on:
  push:
    branches:
      - gtest
  pull_request:
    branches:
      - gtest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Cache APT packages
    - name: Cache APT packages
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt/archives
        key: apt-cache-${{ runner.os }}-${{ hashFiles('.github/workflows/build.yml') }}
        restore-keys: apt-cache-${{ runner.os }}-

    - name: Install Dependencies (Only If Cache Misses)
      run: |
        if [ ! -f "/usr/bin/cmake" ]; then
          sudo apt-get update
          sudo apt-get install -y cmake g++ make ccache
        else
          echo "Dependencies already installed, skipping..."
        fi

    # Cache GoogleTest
    - name: Cache GoogleTest Build
      uses: actions/cache@v3
      with:
        path: build/_deps/googletest-src
        key: gtest-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
          gtest-${{ runner.os }}-

    # Cache ccache (compiler cache)
    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ runner.os }}-

    - name: Configure CMake with ccache
      run: |
        cmake -S . -B build \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build Project with ccache
      run: cmake --build build

    - name: Show ccache stats
      run: ccache -s

    - name: Run Tests with CTest (Capture Output)
      id: ctest_run
      run: |
        cd build
        ctest --output-on-failure | tee test_output.log
        test ${PIPESTATUS[0]} -eq 0  # Fail the workflow if tests fail

    - name: Upload Test Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: build/test_output.log
