name: Build and Test

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make

    - name: Configure Project with CMake
      run: |
        cmake -S . -B build

    - name: Build Project
      run: |
        cmake --build build

    - name: Run Tests
      run: |
        ctest --test-dir build -C Debug --output-on-failure > build/test_output.log

    - name: Upload Test Log
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: build/test_output.log
